### ISSUE TITLE
No Update of counts

### ISSUE THREAD

**Issue by synack666** [bgbraga/homeassistant-apsystems#3]
After installation i get one measured value for each sensor, but no more, no update.
Have tried 3 times, same for each try.

**Comment by krizzziz** [comment]
Same here, only on restarting HA the sensors receive update.

**Comment by 86hakan** [comment]
Same here. Only new values when i restart

**Comment by Codingroller** [comment]
First of all, thanks for taking the time to write this integration. 

I have the same problem 

![image](https://user-images.githubusercontent.com/50908178/128394757-0306b08b-cc7f-4d9a-b38b-18e04040a762.png)

Error in log:

```
Logger: homeassistant.helpers.entity
Source: custom_components/apsystems/sensor.py:156
Integration: apsystems (documentation)
First occurred: 6 August 2021, 6:08:42 (183 occurrences)
Last logged: 11:13:42

Update for sensor.apsystems_energy_latest fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 446, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 654, in async_device_update
    raise exc
  File "/config/custom_components/apsystems/sensor.py", line 156, in async_update
    value = value[-1]
IndexError: list index out of range
```

**Comment by Codingroller** [comment]
I'm not familiar with Python or Home assistant development. 
I'm interested however what the following line of code does (starts at line 153 in sensor.py).
```
index = self._metadata[0]
        value = ap_data[index]

 if isinstance(value, list):
            value = value[-1]
```
What does **value[-1]** do here? Go one back in the list?

**Comment by Christophe69480** [comment]
Same here, only on restarting HA the sensors receive update.

**Comment by synack666** [comment]
Seems like it's dead, very very sad!

**Comment by krizzziz** [comment]
So actually for a while this integration is working. Only thing is that I have two updates on 1 day concerning information from solar panels to home assistant. Around 13.10 and 18.10 every day. Anyone knows where I can change some code to spread it out a little bit more over the day or to add maybe some more updates. Or is this limited?

**Comment by wtrdk** [comment]
Same problem here, I'm trying to figure out why it doesn't update frequently, but no result yet...

**Comment by synack666** [comment]
fixed in fork
https://github.com/skelgaard/homeassistant-apsystems
