### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by danilodene** [bgbraga/homeassistant-apsystems#7]
As of today this integration has stopped working because AP Systems has added a verification code to their login page

![image](https://user-images.githubusercontent.com/5453097/153643810-f87116c8-bea8-40f9-abd3-b193f8462f64.png)

**Comment by andrebbruno** [comment]
Yes I think this one is dead - one other guy has a fork but did not update anything as of yet - https://github.com/skelgaard/homeassistant-apsystems
 @bgbraga are you still supporting this one?

**Comment by artupi** [comment]
If you don't care about privacy of production data there's option in setup to 
![image](https://user-images.githubusercontent.com/96198721/153648560-08760c04-d511-4ffc-9664-3598c03ba332.png)
This will generate Autorized id, which can be used to build link to access data without login. Link can be build like this:
https://apsystemsema.com/ema/intoDemoUser.action?id=hereGoesAutrizeId&locale=en_US.
@bgbraga can you change integration to workaround captcha problem if there's no other way?

Artur

**Comment by andrebbruno** [comment]
@skelgaard - any chance to have this option?

**Comment by skelgaard** [comment]
that is the option i'm working on to get to work on. as said on my own issue, i'm not a python coder, so i have to learn how to use thoose python functions to get around it... but i hope to have something working within the next couple of days

**Comment by artupi** [comment]
Hi,

I found solution to workaround CAPTCHA problem by not using APSystems web page at all. I'm scraping my ECU-C unit to get current production data. To  create max power entity I use home assistant's sql platform with query like:
`
  - platform: sql
    queries:
      - name: "Max Power dzień"
        query: >
          SELECT MAX(CAST(state as decimal)) "MaxPowerToday" FROM states 
          WHERE entity_id = "sensor.ostatania_zarejestrowna_Power"  
          AND state != "unknown"
          AND state != ""
          AND state !="unavailable"
          AND date(created) = date(date("now"));
        column: "MaxPowerToday"
        unit_of_measurement: "W"


`
I still hope that @skelgaard will manage to update the integration. This is just in case.

Artur

**Comment by dclobato** [comment]
> Hi,
> 
> I found solution to workaround CAPTCHA problem by not using APSystems web page at all. I'm scraping my ECU-C unit to get current production data. To create max power entity I use home assistant's sql platform with query like: `
> 
> * platform: sql
>   queries:
>   
>   * name: "Max Power dzień"
>     query: >
>     SELECT MAX(CAST(state as decimal)) "MaxPowerToday" FROM states
>     WHERE entity_id = "sensor.ostatania_zarejestrowna_Power"
>     AND state != "unknown"
>     AND state != ""
>     AND state !="unavailable"
>     AND date(created) = date(date("now"));
>     column: "MaxPowerToday"
>     unit_of_measurement: "W"
> 
> ` I still hope that @skelgaard will manage to update the integration. This is just in case.
> 
> Artur

There is another integration that queries the ECU directly.  I'm using it

https://github.com/ksheumaker/homeassistant-apsystems_ecur

**Comment by artupi** [comment]
This is for different type of ECU (ECU-R). I tested it but it hanged up after a day of work.
Artur

**Comment by andrebbruno** [comment]
> This is for different type of ECU (ECU-R). I tested it but it hanged up after a day of work. Artur

I was able to install just fine, but will wait for a few days to see if it´s good or not. In the github´s page, it states some problems with capturing data and one thing that might help is to turn it off during the night because of systems update, did you try just in case?

**Comment by skelgaard** [comment]
i have pushed a new release on my version with a fix for this... do say if you have any problems with this

**Comment by andrebbruno** [comment]
sounds like they removed captcha now ...

**Comment by danilodene** [comment]
Captcha removed, but the login url has changed. 

I make a pull request to fix it
